In [1]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 경고 뜨지 않게
import warnings
warnings.filterwarnings('ignore')

In [2]:
# 6개 parquet 파일 경로 리스트 
file_list = [
    'open/test/1.회원정보/201807_test_회원정보.parquet',
    'open/test/1.회원정보/201808_test_회원정보.parquet',
    'open/test/1.회원정보/201809_test_회원정보.parquet',
    'open/test/1.회원정보/201810_test_회원정보.parquet',
    'open/test/1.회원정보/201811_test_회원정보.parquet',
    'open/test/1.회원정보/201812_test_회원정보.parquet'
]

# 빈 데이터프레임 리스트 생성
dfs = []

# 각 파일을 읽어서 dfs 리스트에 추가
for file in file_list:
    df = pd.read_parquet(file)
    dfs.append(df)

# 데이터프레임 합치기 (행 기준으로 아래로 붙이기)
merged_df = pd.concat(dfs, ignore_index=True)

In [3]:
# 합친 데이터 확인
print(merged_df.shape)
print(merged_df.head())

(600000, 77)
     기준년월          ID  남녀구분코드   연령  회원여부_이용가능  회원여부_이용가능_CA  회원여부_이용가능_카드론  \
0  201807  TEST_00000       1  40대          1             1              0
1  201807  TEST_00001       1  60대          1             1              0
2  201807  TEST_00002       1  40대          1             1              1
3  201807  TEST_00003       2  40대          1             1              1
4  201807  TEST_00004       2  40대          1             0              1

   소지여부_신용  소지카드수_유효_신용  소지카드수_이용가능_신용  ...  할인금액_제휴연회비_B0M  청구금액_기본연회비_B0M  \
0        1            2              2  ...               0               0
1        1            1              1  ...               0               0
2        1            2              2  ...               0               0
3        1            1              1  ...               0               0
4        1            1              1  ...               0               0

   청구금액_제휴연회비_B0M  상품관련면제카드수_B0M  임직원면제카드수_B0M  우수회원면제카드수_B0M  기타면제카드수_B0M  \
0               0             0개            0개             0개           0개
1               0             0개            0개             0개           0개
2               0             0개            0개             0개           0개
3               0             0개            0개             0개           0개
4               0             0개            0개             0개           0개

   카드신청건수  Life_Stage 최종카드발급경과월
0       0     자녀성장(1)        45
1       0       자녀독립기        19
2       0     자녀성장(1)         5
3       0     자녀성장(1)         7
4       0     자녀성장(1)         1

[5 rows x 77 columns]

In [4]:
# 필요하면 하나로 합친 데이터 저장
merged_df.to_parquet('open/test/1.회원정보/2018_test_회원정보.parquet')

In [5]:
df = pd.read_parquet ('open/test/1.회원정보/2018_test_회원정보.parquet')
df

,기준년월,ID,남녀구분코드,연령,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,소지카드수_이용가능_신용,...,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
0,201807,TEST_00000,1,40대,1,1,0,1,2,2,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),45
1,201807,TEST_00001,1,60대,1,1,0,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀독립기,19
2,201807,TEST_00002,1,40대,1,1,1,1,2,2,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),5
3,201807,TEST_00003,2,40대,1,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),7
4,201807,TEST_00004,2,40대,1,0,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,2,60대,0,0,0,0,0,0,...,0,0,0,0개,0개,0개,0개,0,노년생활,0
599996,201812,TEST_99996,1,30대,1,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀출산기,12
599997,201812,TEST_99997,2,30대,1,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),11
599998,201812,TEST_99998,1,30대,1,1,1,1,3,3,...,0,0,0,0개,0개,0개,0개,0,가족구축기,1
599999,201812,TEST_99999,1,30대,1,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀출산기,20