In [1]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 경고 뜨지 않게
import warnings
warnings.filterwarnings('ignore')

In [2]:
# 6개 parquet 파일 경로 리스트 
file_list = [
    'open/test/3.승인매출정보/201807_test_승인매출정보.parquet',
    'open/test/3.승인매출정보/201808_test_승인매출정보.parquet',
    'open/test/3.승인매출정보/201809_test_승인매출정보.parquet',
    'open/test/3.승인매출정보/201810_test_승인매출정보.parquet',
    'open/test/3.승인매출정보/201811_test_승인매출정보.parquet',
    'open/test/3.승인매출정보/201812_test_승인매출정보.parquet'
]

# 빈 데이터프레임 리스트 생성
dfs = []

# 각 파일을 읽어서 dfs 리스트에 추가
for file in file_list:
    df = pd.read_parquet(file)
    dfs.append(df)

# 데이터프레임 합치기 (행 기준으로 아래로 붙이기)
merged_df = pd.concat(dfs, ignore_index=True)

In [3]:
# 합친 데이터 확인
print(merged_df.shape)
print(merged_df.head())

(600000, 406)
     기준년월          ID  최종이용일자_기본  최종이용일자_신판  최종이용일자_CA  최종이용일자_카드론  최종이용일자_체크  \
0  201807  TEST_00000   20180731   20180731      10101       10101      10101
1  201807  TEST_00001   20180725   20180725   20170710    20171107   20180731
2  201807  TEST_00002   20180711   20180711      10101       10101      10101
3  201807  TEST_00003   20180731   20180731   20150822    20150801      10101
4  201807  TEST_00004   20180716   20180716   20130917       10101   20180707

   최종이용일자_일시불  최종이용일자_할부  이용건수_신용_B0M  ...  승인거절건수_한도초과_B0M  승인거절건수_BL_B0M  \
0    20180731   20160913           28  ...                0              0
1    20180725   20180722            8  ...                0              0
2    20180711   20160703           59  ...                0              0
3    20180731   20160701           37  ...                0              0
4    20180716   20180708           19  ...                0              0

   승인거절건수_입력오류_B0M  승인거절건수_기타_B0M  승인거절건수_R3M  승인거절건수_한도초과_R3M  승인거절건수_BL_R3M  \
0                0              0           0                0              0
1                0              0           0                0              0
2                0              0           3                3              0
3                0              0           0                0              0
4                0              0           0                0              0

   승인거절건수_입력오류_R3M  승인거절건수_기타_R3M      이용금액대
0                0              0   02.50만원+
1                0              0   02.50만원+
2                0              0  01.100만원+
3                0              0   04.10만원+
4                0              0   03.30만원+

[5 rows x 406 columns]

In [4]:
# 필요하면 하나로 합친 데이터 저장
merged_df.to_parquet('open/test/3.승인매출정보/2018_test_승인매출정보.parquet')

In [5]:
df = pd.read_parquet ('open/test/3.승인매출정보/2018_test_승인매출정보.parquet')
df

,기준년월,ID,최종이용일자_기본,최종이용일자_신판,최종이용일자_CA,최종이용일자_카드론,최종이용일자_체크,최종이용일자_일시불,최종이용일자_할부,이용건수_신용_B0M,...,승인거절건수_한도초과_B0M,승인거절건수_BL_B0M,승인거절건수_입력오류_B0M,승인거절건수_기타_B0M,승인거절건수_R3M,승인거절건수_한도초과_R3M,승인거절건수_BL_R3M,승인거절건수_입력오류_R3M,승인거절건수_기타_R3M,이용금액대
0,201807,TEST_00000,20180731,20180731,10101,10101,10101,20180731,20160913,28,...,0,0,0,0,0,0,0,0,0,02.50만원+
1,201807,TEST_00001,20180725,20180725,20170710,20171107,20180731,20180725,20180722,8,...,0,0,0,0,0,0,0,0,0,02.50만원+
2,201807,TEST_00002,20180711,20180711,10101,10101,10101,20180711,20160703,59,...,0,0,0,0,3,3,0,0,0,01.100만원+
3,201807,TEST_00003,20180731,20180731,20150822,20150801,10101,20180731,20160701,37,...,0,0,0,0,0,0,0,0,0,04.10만원+
4,201807,TEST_00004,20180716,20180716,20130917,10101,20180707,20180716,20180708,19,...,0,0,0,0,0,0,0,0,0,03.30만원+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,20170228,20170228,10101,10101,10101,20170228,10101,-1,...,0,0,0,0,0,0,0,0,0,09.미사용
599996,201812,TEST_99996,20181130,20181130,10101,10101,10101,20181130,10101,0,...,0,0,0,0,0,0,0,0,0,05.10만원-
599997,201812,TEST_99997,10101,10101,10101,10101,10101,10101,10101,3,...,0,0,0,0,0,0,0,0,0,09.미사용
599998,201812,TEST_99998,20181230,20181230,10101,10101,20181225,20181230,20180608,78,...,0,0,0,0,0,0,0,0,0,01.100만원+
599999,201812,TEST_99999,20181205,20181205,10101,10101,10101,20181205,10101,1,...,0,0,0,0,0,0,0,0,0,05.10만원-