In [1]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 경고 뜨지 않게
import warnings
warnings.filterwarnings('ignore')

In [2]:
# 6개 parquet 파일 경로 리스트 
file_list = [
    'open/test/6.채널정보/201807_test_채널정보.parquet',
    'open/test/6.채널정보/201808_test_채널정보.parquet',
    'open/test/6.채널정보/201809_test_채널정보.parquet',
    'open/test/6.채널정보/201810_test_채널정보.parquet',
    'open/test/6.채널정보/201811_test_채널정보.parquet',
    'open/test/6.채널정보/201812_test_채널정보.parquet',
]

# 빈 데이터프레임 리스트 생성
dfs = []

# 각 파일을 읽어서 dfs 리스트에 추가
for file in file_list:
    df = pd.read_parquet(file)
    dfs.append(df)

# 데이터프레임 합치기 (행 기준으로 아래로 붙이기)
merged_df = pd.concat(dfs, ignore_index=True)

In [3]:
# 합친 데이터 확인
print(merged_df.shape)
print(merged_df.head())

(600000, 105)
     기준년월          ID 인입횟수_ARS_R6M 이용메뉴건수_ARS_R6M  인입일수_ARS_R6M  인입월수_ARS_R6M  \
0  201807  TEST_00000        1회 이상          1회 이상             0             0
1  201807  TEST_00001        1회 이상          1회 이상             1             1
2  201807  TEST_00002        1회 이상          1회 이상             1             1
3  201807  TEST_00003        1회 이상          1회 이상             2             1
4  201807  TEST_00004        1회 이상          1회 이상             1             1

   인입후경과월_ARS  인입횟수_ARS_B0M  이용메뉴건수_ARS_B0M  인입일수_ARS_B0M  ... 당사PAY_방문횟수_R6M  \
0           0             0               0             0  ...              0
1           5             0               0             0  ...              0
2           3             0               0             0  ...              0
3           3             0               0             0  ...              0
4           1             0               0             0  ...              0

  당사PAY_방문월수_R6M  당사멤버쉽_방문횟수_B0M  당사멤버쉽_방문횟수_R6M 당사멤버쉽_방문월수_R6M   OS구분코드  \
0              0               0               0              0      IOS
1              0               0               0              0  Android
2              0               0               2              1  Android
3              0               0               0              0     None
4              0               0               0              0     None

   홈페이지_금융건수_R6M  홈페이지_선결제건수_R6M  홈페이지_금융건수_R3M  홈페이지_선결제건수_R3M
0              0               0              0               0
1              0               0              0               0
2              0               0              0               0
3              0               0              0               0
4              0               0              0               0

[5 rows x 105 columns]

In [4]:
# 필요하면 하나로 합친 데이터 저장
merged_df.to_parquet('open/test/6.채널정보/2018_test_채널정보.parquet')

In [5]:
df = pd.read_parquet ('open/test/6.채널정보/2018_test_채널정보.parquet')
df

,기준년월,ID,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,인입일수_ARS_R6M,인입월수_ARS_R6M,인입후경과월_ARS,인입횟수_ARS_B0M,이용메뉴건수_ARS_B0M,인입일수_ARS_B0M,...,당사PAY_방문횟수_R6M,당사PAY_방문월수_R6M,당사멤버쉽_방문횟수_B0M,당사멤버쉽_방문횟수_R6M,당사멤버쉽_방문월수_R6M,OS구분코드,홈페이지_금융건수_R6M,홈페이지_선결제건수_R6M,홈페이지_금융건수_R3M,홈페이지_선결제건수_R3M
0,201807,TEST_00000,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,IOS,0,0,0,0
1,201807,TEST_00001,1회 이상,1회 이상,1,1,5,0,0,0,...,0,0,0,0,0,Android,0,0,0,0
2,201807,TEST_00002,1회 이상,1회 이상,1,1,3,0,0,0,...,0,0,0,2,1,Android,0,0,0,0
3,201807,TEST_00003,1회 이상,1회 이상,2,1,3,0,0,0,...,0,0,0,0,0,None,0,0,0,0
4,201807,TEST_00004,1회 이상,1회 이상,1,1,1,0,0,0,...,0,0,0,0,0,None,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
599996,201812,TEST_99996,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,3,7,3,3
599997,201812,TEST_99997,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
599998,201812,TEST_99998,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,Android,7,22,4,12
599999,201812,TEST_99999,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0