In [1]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 경고 뜨지 않게
import warnings
warnings.filterwarnings('ignore')

In [2]:
# 6개 parquet 파일 경로 리스트 
file_list = [
    'open/test/2.신용정보/201807_test_신용정보.parquet',
    'open/test/2.신용정보/201808_test_신용정보.parquet',
    'open/test/2.신용정보/201809_test_신용정보.parquet',
    'open/test/2.신용정보/201810_test_신용정보.parquet',
    'open/test/2.신용정보/201811_test_신용정보.parquet',
    'open/test/2.신용정보/201812_test_신용정보.parquet'
]

# 빈 데이터프레임 리스트 생성
dfs = []

# 각 파일을 읽어서 dfs 리스트에 추가
for file in file_list:
    df = pd.read_parquet(file)
    dfs.append(df)

# 데이터프레임 합치기 (행 기준으로 아래로 붙이기)
merged_df = pd.concat(dfs, ignore_index=True)

In [3]:
# 합친 데이터 확인
print(merged_df.shape)
print(merged_df.head())

(600000, 42)
     기준년월          ID  최초한도금액  카드이용한도금액  CA한도금액  일시상환론한도금액  월상환론한도금액  \
0  201807  TEST_00000       0     50902   18131          0         0
1  201807  TEST_00001       0     50080   16819          0         0
2  201807  TEST_00002       0    100045   30505          0     19499
3  201807  TEST_00003       0     18508    6402          0    156102
4  201807  TEST_00004   10000      4033       0      42195     52784

   CA이자율_할인전  CL이자율_할인전  RV일시불이자율_할인전  ...  연체감액여부_R3M  한도심사요청건수  한도요청거절건수  \
0  14.641712  11.894873     10.346302  ...           0        0회         0
1  18.992879  17.600092     14.021300  ...           0        0회         0
2  14.823453  14.817385     10.679822  ...           0        0회         0
3  15.121715  15.284812     11.674446  ...           0        0회         0
4  14.220050  10.897462     10.777585  ...           0        0회         0

   한도심사요청후경과월 한도심사거절후경과월  시장단기연체여부_R6M  시장단기연체여부_R3M  시장연체상환여부_R6M  \
0           3          3             0             0             0
1           3          3             0             0             0
2           3          3             0             0             0
3           3          3             0             0             0
4           3          3             0             0             0

   시장연체상환여부_R3M  rv최초시작후경과일
0             0    99999999
1             0    99999999
2             0    99999999
3             0    99999999
4             0    99999999

[5 rows x 42 columns]

In [4]:
# 필요하면 하나로 합친 데이터 저장
merged_df.to_parquet('open/test/2.신용정보/2018_test_신용정보.parquet')

In [5]:
df = pd.read_parquet ('open/test/2.신용정보/2018_test_신용정보.parquet')
df

,기준년월,ID,최초한도금액,카드이용한도금액,CA한도금액,일시상환론한도금액,월상환론한도금액,CA이자율_할인전,CL이자율_할인전,RV일시불이자율_할인전,...,연체감액여부_R3M,한도심사요청건수,한도요청거절건수,한도심사요청후경과월,한도심사거절후경과월,시장단기연체여부_R6M,시장단기연체여부_R3M,시장연체상환여부_R6M,시장연체상환여부_R3M,rv최초시작후경과일
0,201807,TEST_00000,0,50902,18131,0,0,14.641712,11.894873,10.346302,...,0,0회,0,3,3,0,0,0,0,99999999
1,201807,TEST_00001,0,50080,16819,0,0,18.992879,17.600092,14.021300,...,0,0회,0,3,3,0,0,0,0,99999999
2,201807,TEST_00002,0,100045,30505,0,19499,14.823453,14.817385,10.679822,...,0,0회,0,3,3,0,0,0,0,99999999
3,201807,TEST_00003,0,18508,6402,0,156102,15.121715,15.284812,11.674446,...,0,0회,0,3,3,0,0,0,0,99999999
4,201807,TEST_00004,10000,4033,0,42195,52784,14.220050,10.897462,10.777585,...,0,0회,0,3,3,0,0,0,0,99999999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,0,0,14.642972,11.898260,10.674317,...,0,0회,0,3,3,0,0,0,0,99999999
599996,201812,TEST_99996,0,49025,17876,48022,152797,14.221370,14.901302,10.324015,...,0,0회,0,3,3,0,0,0,0,99999999
599997,201812,TEST_99997,0,29996,13332,89997,156313,15.207480,11.902432,11.495748,...,0,0회,0,3,3,0,0,0,0,99999999
599998,201812,TEST_99998,0,42610,17362,90003,204480,15.268772,15.299862,11.264263,...,0,0회,0,3,3,0,0,0,0,99999999
599999,201812,TEST_99999,0,86444,30242,90002,180635,14.722716,11.899745,11.089403,...,0,0회,0,3,3,0,0,0,0,99999999