In [1]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 경고 뜨지 않게
import warnings
warnings.filterwarnings('ignore')

In [2]:
# 6개 parquet 파일 경로 리스트 
file_list = [
    'open/train/3.승인매출정보/201807_train_승인매출정보.parquet',
    'open/train/3.승인매출정보/201808_train_승인매출정보.parquet',
    'open/train/3.승인매출정보/201809_train_승인매출정보.parquet',
    'open/train/3.승인매출정보/201810_train_승인매출정보.parquet',
    'open/train/3.승인매출정보/201811_train_승인매출정보.parquet',
    'open/train/3.승인매출정보/201812_train_승인매출정보.parquet'
]

# 빈 데이터프레임 리스트 생성
dfs = []

# 각 파일을 읽어서 dfs 리스트에 추가
for file in file_list:
    df = pd.read_parquet(file)
    dfs.append(df)

# 데이터프레임 합치기 (행 기준으로 아래로 붙이기)
merged_df = pd.concat(dfs, ignore_index=True)

In [3]:
# 합친 데이터 확인
print(merged_df.shape)
print(merged_df.head())

(2400000, 406)
     기준년월            ID  최종이용일자_기본  최종이용일자_신판  최종이용일자_CA  최종이용일자_카드론  \
0  201807  TRAIN_000000   20180719   20180713   20180719       10101
1  201807  TRAIN_000001   20180719   20180719   20170728    20170327
2  201807  TRAIN_000002   20180706   20180706   20180706    20151119
3  201807  TRAIN_000003   20180721   20180715   20180721       10101
4  201807  TRAIN_000004   20180124   20180124      10101       10101

   최종이용일자_체크  최종이용일자_일시불  최종이용일자_할부  이용건수_신용_B0M  ...  승인거절건수_한도초과_B0M  \
0   20180203    20180709   20180713           11  ...                0
1      10101    20180719   20171231           13  ...                0
2   20141230    20180706   20180627           12  ...                0
3   20141111    20180704   20180715            6  ...                0
4   20180512    20180124      10101           -2  ...                0

   승인거절건수_BL_B0M  승인거절건수_입력오류_B0M  승인거절건수_기타_B0M  승인거절건수_R3M  승인거절건수_한도초과_R3M  \
0              0                0              0           3                3
1              0                0              0           3                3
2              0                0              0           0                0
3              0                0              0           3                3
4              0                0              0           0                0

   승인거절건수_BL_R3M  승인거절건수_입력오류_R3M  승인거절건수_기타_R3M      이용금액대
0              0                0              0  01.100만원+
1              0                0              0   03.30만원+
2              0                0              0  01.100만원+
3              0                0              0  01.100만원+
4              0                0              0     09.미사용

[5 rows x 406 columns]

In [4]:
# 필요하면 하나로 합친 데이터 저장
merged_df.to_parquet('open/train/3.승인매출정보/2018_train_승인매출정보.parquet')

In [5]:
df = pd.read_parquet ('open/train/3.승인매출정보/2018_train_승인매출정보.parquet')
df

,기준년월,ID,최종이용일자_기본,최종이용일자_신판,최종이용일자_CA,최종이용일자_카드론,최종이용일자_체크,최종이용일자_일시불,최종이용일자_할부,이용건수_신용_B0M,...,승인거절건수_한도초과_B0M,승인거절건수_BL_B0M,승인거절건수_입력오류_B0M,승인거절건수_기타_B0M,승인거절건수_R3M,승인거절건수_한도초과_R3M,승인거절건수_BL_R3M,승인거절건수_입력오류_R3M,승인거절건수_기타_R3M,이용금액대
0,201807,TRAIN_000000,20180719,20180713,20180719,10101,20180203,20180709,20180713,11,...,0,0,0,0,3,3,0,0,0,01.100만원+
1,201807,TRAIN_000001,20180719,20180719,20170728,20170327,10101,20180719,20171231,13,...,0,0,0,0,3,3,0,0,0,03.30만원+
2,201807,TRAIN_000002,20180706,20180706,20180706,20151119,20141230,20180706,20180627,12,...,0,0,0,0,0,0,0,0,0,01.100만원+
3,201807,TRAIN_000003,20180721,20180715,20180721,10101,20141111,20180704,20180715,6,...,0,0,0,0,3,3,0,0,0,01.100만원+
4,201807,TRAIN_000004,20180124,20180124,10101,10101,20180512,20180124,10101,-2,...,0,0,0,0,0,0,0,0,0,09.미사용
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,20181220,20181220,10101,10101,20181212,20181220,20160501,2,...,0,0,0,0,0,0,0,0,0,09.미사용
2399996,201812,TRAIN_399996,20181202,20181202,10101,20170112,10101,20181202,20180112,10,...,0,0,0,0,0,0,0,0,0,01.100만원+
2399997,201812,TRAIN_399997,20181230,20181230,10101,10101,20131124,20181230,20180919,10,...,0,0,0,0,0,0,0,0,0,02.50만원+
2399998,201812,TRAIN_399998,20161224,20161224,10101,10101,10101,20161224,20150122,-2,...,0,0,0,0,0,0,0,0,0,09.미사용
2399999,201812,TRAIN_399999,20180831,20180831,10101,10101,10101,20180831,20180713,-1,...,0,0,0,0,0,0,0,0,0,04.10만원+