In [1]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 경고 뜨지 않게
import warnings
warnings.filterwarnings('ignore')

In [2]:
# 6개 parquet 파일 경로 리스트 
file_list = [
    'open/train/8.성과정보/201807_train_성과정보.parquet',
    'open/train/8.성과정보/201808_train_성과정보.parquet',
    'open/train/8.성과정보/201809_train_성과정보.parquet',
    'open/train/8.성과정보/201810_train_성과정보.parquet',
    'open/train/8.성과정보/201811_train_성과정보.parquet',
    'open/train/8.성과정보/201812_train_성과정보.parquet'
]

# 빈 데이터프레임 리스트 생성
dfs = []

# 각 파일을 읽어서 dfs 리스트에 추가
for file in file_list:
    df = pd.read_parquet(file)
    dfs.append(df)

# 데이터프레임 합치기 (행 기준으로 아래로 붙이기)
merged_df = pd.concat(dfs, ignore_index=True)

In [3]:
# 합친 데이터 확인
print(merged_df.shape)
print(merged_df.head())

(2400000, 49)
     기준년월            ID  증감율_이용건수_신용_전월  증감율_이용건수_신판_전월  증감율_이용건수_일시불_전월  \
0  201807  TRAIN_000000        0.454548        0.454548         0.364727
1  201807  TRAIN_000001       -0.511808       -0.511808        -0.511808
2  201807  TRAIN_000002       -0.062716       -0.062716         0.067843
3  201807  TRAIN_000003        0.135707        0.135707         0.153975
4  201807  TRAIN_000004        0.000000        0.000000         0.000000

   증감율_이용건수_할부_전월  증감율_이용건수_CA_전월  증감율_이용건수_체크_전월  증감율_이용건수_카드론_전월  \
0        1.999996             0.0             0.0              0.0
1        0.000000             0.0             0.0              0.0
2       -1.999996             0.0             0.0              0.0
3       -1.999996             0.0             0.0              0.0
4        0.000000             0.0             0.0              0.0

   증감율_이용금액_신용_전월  ...  변동률_RV일시불평잔  변동률_할부평잔  변동률_CA평잔  변동률_RVCA평잔  \
0        0.409766  ...     0.999998  1.042805  0.999700    0.999998
1       -1.010817  ...     1.092698  0.905663  0.999998    0.999998
2       -0.902166  ...     1.006124  1.993590  0.852567    0.999998
3       -0.866052  ...     0.999998  1.050646  0.999877    0.999998
4        0.000028  ...     0.999998  0.999998  0.999998    0.999998

   변동률_카드론평잔  변동률_잔액_B1M  변동률_잔액_일시불_B1M  변동률_잔액_CA_B1M  혜택수혜율_R3M  혜택수혜율_B0M
0   0.999998    0.261886        0.270752       0.000000   1.044401   1.280543
1   0.999998   -0.563388       -0.670348       0.000000   0.000000   0.000000
2   0.999998   -0.046516        0.058114      -0.014191   0.524159   1.208420
3   0.999998    0.023821        0.258943       0.000000   0.880925   1.657124
4   0.999998    0.000000        0.000000       0.000000        NaN        NaN

[5 rows x 49 columns]

In [4]:
# 필요하면 하나로 합친 데이터 저장
merged_df.to_parquet('open/train/8.성과정보/2018_train_성과정보.parquet')

In [5]:
df = pd.read_parquet ('open/train/8.성과정보/2018_train_성과정보.parquet')
df

,기준년월,ID,증감율_이용건수_신용_전월,증감율_이용건수_신판_전월,증감율_이용건수_일시불_전월,증감율_이용건수_할부_전월,증감율_이용건수_CA_전월,증감율_이용건수_체크_전월,증감율_이용건수_카드론_전월,증감율_이용금액_신용_전월,...,변동률_RV일시불평잔,변동률_할부평잔,변동률_CA평잔,변동률_RVCA평잔,변동률_카드론평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,변동률_잔액_CA_B1M,혜택수혜율_R3M,혜택수혜율_B0M
0,201807,TRAIN_000000,0.454548,0.454548,0.364727,1.999996,0.0,0.000000,0.0,0.409766,...,0.999998,1.042805,0.999700,0.999998,0.999998,0.261886,0.270752,0.000000,1.044401,1.280543
1,201807,TRAIN_000001,-0.511808,-0.511808,-0.511808,0.000000,0.0,0.000000,0.0,-1.010817,...,1.092698,0.905663,0.999998,0.999998,0.999998,-0.563388,-0.670348,0.000000,0.000000,0.000000
2,201807,TRAIN_000002,-0.062716,-0.062716,0.067843,-1.999996,0.0,0.000000,0.0,-0.902166,...,1.006124,1.993590,0.852567,0.999998,0.999998,-0.046516,0.058114,-0.014191,0.524159,1.208420
3,201807,TRAIN_000003,0.135707,0.135707,0.153975,-1.999996,0.0,0.000000,0.0,-0.866052,...,0.999998,1.050646,0.999877,0.999998,0.999998,0.023821,0.258943,0.000000,0.880925,1.657124
4,201807,TRAIN_000004,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000028,...,0.999998,0.999998,0.999998,0.999998,0.999998,0.000000,0.000000,0.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0.000000,0.000000,0.000000,0.000000,0.0,-0.081943,0.0,0.000027,...,0.999998,0.999998,0.999998,0.999998,0.999998,0.000000,0.000000,0.000000,NaN,NaN
2399996,201812,TRAIN_399996,0.073804,0.073804,0.073804,0.000000,0.0,0.000000,0.0,0.207099,...,0.999998,0.999998,0.999998,0.999998,0.921733,-0.203251,-0.159143,0.000000,1.377071,2.533815
2399997,201812,TRAIN_399997,-0.040432,-0.040432,-0.040432,0.000000,0.0,0.000000,0.0,0.254495,...,0.999998,0.345027,0.999998,0.999998,0.999998,0.027319,0.126581,0.000000,0.000000,0.000000
2399998,201812,TRAIN_399998,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000034,...,0.999998,0.999998,0.999998,0.999998,0.999998,0.000000,0.000000,0.000000,NaN,NaN
2399999,201812,TRAIN_399999,0.187598,0.187598,0.187598,0.000000,0.0,0.000000,0.0,0.332268,...,0.999998,0.593160,0.999998,0.999998,0.999998,-0.039845,-0.002659,0.000000,0.000000,0.000000