In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import gc

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 결측치 시각화를 위한 라이브러리
import missingno

In [2]:
# 1. 회원정보
train_df1 = pd.read_parquet('open/train/1.회원정보/2018_train_회원정보.parquet')
test_df1  = pd.read_parquet('open/test/1.회원정보/2018_test_회원정보.parquet')
df1 = pd.concat([train_df1, test_df1], axis=0, ignore_index=True)
print(df1)

# 2. 신용정보
train_df2 = pd.read_parquet('open/train/2.신용정보/2018_train_신용정보.parquet')
test_df2  = pd.read_parquet('open/test/2.신용정보/2018_test_신용정보.parquet')
df2 = pd.concat([train_df2, test_df2], axis=0, ignore_index=True)
print(df2)

# 3. 승인매출정보
train_df3 = pd.read_parquet('open/train/3.승인매출정보/2018_train_승인매출정보.parquet')
test_df3  = pd.read_parquet('open/test/3.승인매출정보/2018_test_승인매출정보.parquet')
df3 = pd.concat([train_df3, test_df3], axis=0, ignore_index=True)
print(df3)

# 4. 청구입금정보
train_df4 = pd.read_parquet('open/train/4.청구입금정보/2018_train_청구입금정보.parquet')
test_df4  = pd.read_parquet('open/test/4.청구입금정보/2018_test_청구입금정보.parquet')
df4 = pd.concat([train_df4, test_df4], axis=0, ignore_index=True)
print(df4)

# 5. 잔액정보
train_df5 = pd.read_parquet('open/train/5.잔액정보/2018_train_잔액정보.parquet')
test_df5  = pd.read_parquet('open/test/5.잔액정보/2018_test_잔액정보.parquet')
df5 = pd.concat([train_df5, test_df5], axis=0, ignore_index=True)
print(df5)

# 6. 채널정보
train_df6 = pd.read_parquet('open/train/6.채널정보/2018_train_채널정보.parquet')
test_df6  = pd.read_parquet('open/test/6.채널정보/2018_test_채널정보.parquet')
df6 = pd.concat([train_df6, test_df6], axis=0, ignore_index=True)
print(df6)

# 7. 마케팅정보
train_df7 = pd.read_parquet('open/train/7.마케팅정보/2018_train_마케팅정보.parquet')
test_df7 = pd.read_parquet('open/test/7.마케팅정보/2018_test_마케팅정보.parquet')
df7 = pd.concat([train_df7, test_df7], axis=0, ignore_index=True)
print(df7)

# 8. 성과정보
train_df8 = pd.read_parquet('open/train/8.성과정보/2018_train_성과정보.parquet')
test_df8 = pd.read_parquet('open/test/8.성과정보/2018_test_성과정보.parquet')
df8 = pd.concat([train_df8, test_df8], axis=0, ignore_index=True)
print(df8)

           기준년월            ID  남녀구분코드   연령 Segment  회원여부_이용가능  회원여부_이용가능_CA  \
0        201807  TRAIN_000000       2  40대       D          1             1
1        201807  TRAIN_000001       1  30대       E          1             1
2        201807  TRAIN_000002       1  30대       C          1             1
3        201807  TRAIN_000003       2  40대       D          1             1
4        201807  TRAIN_000004       2  40대       E          1             1
...         ...           ...     ...  ...     ...        ...           ...
2999995  201812    TEST_99995       2  60대     NaN          0             0
2999996  201812    TEST_99996       1  30대     NaN          1             1
2999997  201812    TEST_99997       2  30대     NaN          1             1
2999998  201812    TEST_99998       1  30대     NaN          1             1
2999999  201812    TEST_99999       1  30대     NaN          1             1

         회원여부_이용가능_카드론  소지여부_신용  소지카드수_유효_신용  ...  할인금액_제휴연회비_B0M  \
0                    0        1            1  ...               0
1                    1        1            1  ...               0
2                    0        1            1  ...               0
3                    0        1            2  ...               0
4                    1        1            1  ...               0
...                ...      ...          ...  ...             ...
2999995              0        0            0  ...               0
2999996              1        1            1  ...               0
2999997              1        1            1  ...               0
2999998              1        1            3  ...               0
2999999              1        1            1  ...               0

         청구금액_기본연회비_B0M  청구금액_제휴연회비_B0M  상품관련면제카드수_B0M  임직원면제카드수_B0M  \
0                     0               0             0개            0개
1                     0               0             0개            0개
2                     0               0             0개            0개
3                     0               0             0개            0개
4                     0               0             0개            0개
...                 ...             ...            ...           ...
2999995               0               0             0개            0개
2999996               0               0             0개            0개
2999997               0               0             0개            0개
2999998               0               0             0개            0개
2999999               0               0             0개            0개

         우수회원면제카드수_B0M  기타면제카드수_B0M  카드신청건수  Life_Stage  최종카드발급경과월
0                   0개           0개       0     자녀성장(2)         22
1                   0개           0개       0     자녀성장(1)         18
2                   0개           0개       0       자녀출산기         20
3                   0개           0개       1     자녀성장(2)         17
4                   0개           0개       1     자녀성장(1)         15
...                ...          ...     ...         ...        ...
2999995             0개           0개       0        노년생활          0
2999996             0개           0개       0       자녀출산기         12
2999997             0개           0개       0     자녀성장(1)         11
2999998             0개           0개       0       가족구축기          1
2999999             0개           0개       0       자녀출산기         20

[3000000 rows x 78 columns]
           기준년월            ID  최초한도금액  카드이용한도금액  CA한도금액  일시상환론한도금액  월상환론한도금액  \
0        201807  TRAIN_000000       0     19354    7270          0         0
1        201807  TRAIN_000001       0      9996    5718      41996     90611
2        201807  TRAIN_000002       0     88193   35207          0         0
3        201807  TRAIN_000003       0     19062    6531          0         0
4        201807  TRAIN_000004       0    177222   47149      48000    155020
...         ...           ...     ...       ...     ...        ...       ...
2999995  201812    TEST_99995       0         0       0          0         0
2999996  201812    TEST_99996       0     49025   17876      48022    152797
2999997  201812    TEST_99997       0     29996   13332      89997    156313
2999998  201812    TEST_99998       0     42610   17362      90003    204480
2999999  201812    TEST_99999       0     86444   30242      90002    180635

         CA이자율_할인전  CL이자율_할인전  RV일시불이자율_할인전  ...  연체감액여부_R3M  한도심사요청건수  \
0        22.995207  18.254978     17.264967  ...           0        0회
1        14.793821  14.834873     10.622446  ...           0        0회
2        22.014276  17.875321     17.155829  ...           0        0회
3        22.998014  22.999453     19.293674  ...           0        0회
4        14.661948  10.897410     10.654587  ...           0        0회
...            ...        ...           ...  ...         ...       ...
2999995  14.642972  11.898260     10.674317  ...           0        0회
2999996  14.221370  14.901302     10.324015  ...           0        0회
2999997  15.207480  11.902432     11.495748  ...           0        0회
2999998  15.268772  15.299862     11.264263  ...           0        0회
2999999  14.722716  11.899745     11.089403  ...           0        0회

         한도요청거절건수  한도심사요청후경과월 한도심사거절후경과월  시장단기연체여부_R6M  시장단기연체여부_R3M  \
0               0           3          3             0             0
1               0           3          3             0             0
2               0           3          3             0             0
3               0           3          3             0             0
4               0           3          3             0             0
...           ...         ...        ...           ...           ...
2999995         0           3          3             0             0
2999996         0           3          3             0             0
2999997         0           3          3             0             0
2999998         0           3          3             0             0
2999999         0           3          3             0             0

         시장연체상환여부_R6M  시장연체상환여부_R3M  rv최초시작후경과일
0                   0             0    99999999
1                   0             0         322
2                   0             0        2378
3                   0             0    99999999
4                   0             0    99999999
...               ...           ...         ...
2999995             0             0    99999999
2999996             0             0    99999999
2999997             0             0    99999999
2999998             0             0    99999999
2999999             0             0    99999999

[3000000 rows x 42 columns]
           기준년월            ID  최종이용일자_기본  최종이용일자_신판  최종이용일자_CA  최종이용일자_카드론  \
0        201807  TRAIN_000000   20180719   20180713   20180719       10101
1        201807  TRAIN_000001   20180719   20180719   20170728    20170327
2        201807  TRAIN_000002   20180706   20180706   20180706    20151119
3        201807  TRAIN_000003   20180721   20180715   20180721       10101
4        201807  TRAIN_000004   20180124   20180124      10101       10101
...         ...           ...        ...        ...        ...         ...
2999995  201812    TEST_99995   20170228   20170228      10101       10101
2999996  201812    TEST_99996   20181130   20181130      10101       10101
2999997  201812    TEST_99997      10101      10101      10101       10101
2999998  201812    TEST_99998   20181230   20181230      10101       10101
2999999  201812    TEST_99999   20181205   20181205      10101       10101

         최종이용일자_체크  최종이용일자_일시불  최종이용일자_할부  이용건수_신용_B0M  ...  승인거절건수_한도초과_B0M  \
0         20180203    20180709   20180713           11  ...                0
1            10101    20180719   20171231           13  ...                0
2         20141230    20180706   20180627           12  ...                0
3         20141111    20180704   20180715            6  ...                0
4         20180512    20180124      10101           -2  ...                0
...            ...         ...        ...          ...  ...              ...
2999995      10101    20170228      10101           -1  ...                0
2999996      10101    20181130      10101            0  ...                0
2999997      10101       10101      10101            3  ...                0
2999998   20181225    20181230   20180608           78  ...                0
2999999      10101    20181205      10101            1  ...                0

         승인거절건수_BL_B0M  승인거절건수_입력오류_B0M  승인거절건수_기타_B0M  승인거절건수_R3M  \
0                    0                0              0           3
1                    0                0              0           3
2                    0                0              0           0
3                    0                0              0           3
4                    0                0              0           0
...                ...              ...            ...         ...
2999995              0                0              0           0
2999996              0                0              0           0
2999997              0                0              0           0
2999998              0                0              0           0
2999999              0                0              0           0

         승인거절건수_한도초과_R3M  승인거절건수_BL_R3M  승인거절건수_입력오류_R3M  승인거절건수_기타_R3M  \
0                      3              0                0              0
1                      3              0                0              0
2                      0              0                0              0
3                      3              0                0              0
4                      0              0                0              0
...                  ...            ...              ...            ...
2999995                0              0                0              0
2999996                0              0                0              0
2999997                0              0                0              0
2999998                0              0                0              0
2999999                0              0                0              0

             이용금액대
0        01.100만원+
1         03.30만원+
2        01.100만원+
3        01.100만원+
4           09.미사용
...            ...
2999995     09.미사용
2999996   05.10만원-
2999997     09.미사용
2999998  01.100만원+
2999999   05.10만원-

[3000000 rows x 406 columns]
           기준년월            ID  대표결제일 대표결제방법코드 대표청구지고객주소구분코드 대표청구서수령지구분코드  \
0        201807  TRAIN_000000     27     자동이체           미확인    당사페이앱+이메일
1        201807  TRAIN_000001     13     자동이체           주거지           우편
2        201807  TRAIN_000002      1     자동이체           미확인          이메일
3        201807  TRAIN_000003      5     자동이체           주거지           우편
4        201807  TRAIN_000004     13     자동이체           주거지           우편
...         ...           ...    ...      ...           ...          ...
2999995  201812    TEST_99995     20     자동이체            회사           우편
2999996  201812    TEST_99996     20     자동이체           주거지           우편
2999997  201812    TEST_99997     15     자동이체           미확인          이메일
2999998  201812    TEST_99998     12     자동이체           미확인    K톡명세서+이메일
2999999  201812    TEST_99999      5     자동이체           주거지           우편

        청구서수령방법  청구서발송여부_B0  청구서발송여부_R3M  청구서발송여부_R6M  ...  할인금액_청구서_B0M  \
0         문자메세지           1            1            1  ...             0
1            우편           1            1            1  ...           163
2           이메일           1            1            1  ...             0
3            우편           1            1            1  ...             0
4            우편           0            1            1  ...             0
...         ...         ...          ...          ...  ...           ...
2999995      우편           0            0            0  ...             0
2999996      우편           1            1            1  ...            50
2999997     이메일           0            0            0  ...             0
2999998      K톡           1            1            1  ...           242
2999999      우편           1            1            1  ...             0

         상환개월수_결제일_R6M  상환개월수_결제일_R3M  선결제건수_R6M  선결제건수_R3M  연체건수_R6M  \
0                    5              3          0          0         1
1                    6              3          0          0         0
2                    6              3          0          0         0
3                    5              3          2          0         0
4                    1              1          0          0         0
...                ...            ...        ...        ...       ...
2999995              0              0          0          0         0
2999996              5              3          3          2         0
2999997              0              0          0          0         0
2999998              1              1          7          3         0
2999999              6              3          0          0         0

         연체건수_R3M  혜택수혜금액_R3M  포인트_마일리지_환산_B0M  혜택수혜금액
0               0           3                0       0
1               0           0                0       0
2               0         121                0      50
3               0           3                0       2
4               0           0                0       0
...           ...         ...              ...     ...
2999995         0           0                0       0
2999996         0         149                0      49
2999997         0           0                0       0
2999998         0           0                0       0
2999999         0           0                0       0

[3000000 rows x 46 columns]
           기준년월            ID  잔액_일시불_B0M  잔액_할부_B0M  잔액_현금서비스_B0M  \
0        201807  TRAIN_000000         998        962         22971
1        201807  TRAIN_000001        2565       2390             0
2        201807  TRAIN_000002        5312       5113         21531
3        201807  TRAIN_000003         730       5025         26284
4        201807  TRAIN_000004           0          0             0
...         ...           ...         ...        ...           ...
2999995  201812    TEST_99995           0          0             0
2999996  201812    TEST_99996         191          0             0
2999997  201812    TEST_99997           0          0             0
2999998  201812    TEST_99998       17916       2786             0
2999999  201812    TEST_99999          44          0             0

         잔액_리볼빙일시불이월_B0M  잔액_리볼빙CA이월_B0M  잔액_카드론_B0M  월중평잔_일시불_B0M  \
0                      0               0           0          1084
1                      0               0           0          4090
2                   6795               0           0          5006
3                      0               0           0           487
4                      0               0           0             0
...                  ...             ...         ...           ...
2999995                0               0           0             0
2999996                0               0           0           260
2999997                0               0           0             0
2999998                0               0           0         16911
2999999                0               0           0            37

         월중평잔_할부_B0M  ...  평잔_6M  평잔_일시불_6M  평잔_일시불_해외_6M  평잔_RV일시불_6M  \
0                547  ...  15988       2440             0            0
1               2553  ...   7045       2677             0         2830
2               8778  ...  66549       9118             0         8870
3               5607  ...  30139        884             0            0
4                  0  ...     28         21             0            0
...              ...  ...    ...        ...           ...          ...
2999995            0  ...      0          0             0            0
2999996            0  ...    275        137             0            0
2999997            0  ...      0          0             0            0
2999998         2081  ...  20549      18108           240            0
2999999            0  ...     18          9             0            0

         평잔_RV일시불_해외_6M  평잔_할부_6M  평잔_할부_해외_6M  평잔_CA_6M  평잔_CA_해외_6M  \
0                     0       572            0     17008            0
1                     0      2736            0         0            0
2                     0      4429            0     43351            0
3                     0      5097            0     30697            0
4                     0         0            0         0            0
...                 ...       ...          ...       ...          ...
2999995               0         0            0         0            0
2999996               0         0            0         0            0
2999997               0         0            0         0            0
2999998               0      1830            0         0            0
2999999               0         0            0         0            0

         평잔_카드론_6M
0                0
1                0
2                0
3                0
4                0
...            ...
2999995          0
2999996          0
2999997          0
2999998          0
2999999          0

[3000000 rows x 82 columns]
           기준년월            ID 인입횟수_ARS_R6M 이용메뉴건수_ARS_R6M  인입일수_ARS_R6M  \
0        201807  TRAIN_000000       10회 이상         10회 이상             8
1        201807  TRAIN_000001        1회 이상          1회 이상             0
2        201807  TRAIN_000002        1회 이상          1회 이상             1
3        201807  TRAIN_000003       10회 이상         10회 이상            10
4        201807  TRAIN_000004        1회 이상          1회 이상             0
...         ...           ...          ...            ...           ...
2999995  201812    TEST_99995        1회 이상          1회 이상             0
2999996  201812    TEST_99996        1회 이상          1회 이상             0
2999997  201812    TEST_99997        1회 이상          1회 이상             0
2999998  201812    TEST_99998        1회 이상          1회 이상             0
2999999  201812    TEST_99999        1회 이상          1회 이상             0

         인입월수_ARS_R6M  인입후경과월_ARS  인입횟수_ARS_B0M  이용메뉴건수_ARS_B0M  인입일수_ARS_B0M  \
0                   6           0             2               6             2
1                   0           0             0               0             0
2                   1           0             2               5             1
3                   6           0             2               6             2
4                   0           0             0               0             0
...               ...         ...           ...             ...           ...
2999995             0           0             0               0             0
2999996             0           0             0               0             0
2999997             0           0             0               0             0
2999998             0           0             0               0             0
2999999             0           0             0               0             0

         ... 당사PAY_방문횟수_R6M 당사PAY_방문월수_R6M  당사멤버쉽_방문횟수_B0M  당사멤버쉽_방문횟수_R6M  \
0        ...              0              0              22             221
1        ...              0              0               0               0
2        ...              0              0               0               0
3        ...              0              0              23             219
4        ...              0              0               0               0
...      ...            ...            ...             ...             ...
2999995  ...              0              0               0               0
2999996  ...              0              0               0               0
2999997  ...              0              0               0               0
2999998  ...              0              0               0               0
2999999  ...              0              0               0               0


In [3]:
# 필요하면 하나로 합친 데이터 저장
df1.to_parquet('2018_회원정보.parquet', index=False)
df2.to_parquet('2018_신용정보.parquet', index=False)
df3.to_parquet('2018_승인매출정보.parquet', index=False)
df4.to_parquet('2018_청구입금정보.parquet', index=False)
df5.to_parquet('2018_잔액정보.parquet', index=False)
df6.to_parquet('2018_채널정보.parquet', index=False)
df7.to_parquet('2018_마케팅정보.parquet', index=False)
df8.to_parquet('2018_성과정보.parquet', index=False)