In [1]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 경고 뜨지 않게
import warnings
warnings.filterwarnings('ignore')

In [2]:
# 6개 parquet 파일 경로 리스트 
file_list = [
    'open/train/1.회원정보/201807_train_회원정보.parquet',
    'open/train/1.회원정보/201808_train_회원정보.parquet',
    'open/train/1.회원정보/201809_train_회원정보.parquet',
    'open/train/1.회원정보/201810_train_회원정보.parquet',
    'open/train/1.회원정보/201811_train_회원정보.parquet',
    'open/train/1.회원정보/201812_train_회원정보.parquet'
]

# 빈 데이터프레임 리스트 생성
dfs = []

# 각 파일을 읽어서 dfs 리스트에 추가
for file in file_list:
    df = pd.read_parquet(file)
    dfs.append(df)

# 데이터프레임 합치기 (행 기준으로 아래로 붙이기)
merged_df = pd.concat(dfs, ignore_index=True)

In [3]:
# 합친 데이터 확인
print(merged_df.shape)
print(merged_df.head())

(2400000, 78)
     기준년월            ID  남녀구분코드   연령 Segment  회원여부_이용가능  회원여부_이용가능_CA  \
0  201807  TRAIN_000000       2  40대       D          1             1
1  201807  TRAIN_000001       1  30대       E          1             1
2  201807  TRAIN_000002       1  30대       C          1             1
3  201807  TRAIN_000003       2  40대       D          1             1
4  201807  TRAIN_000004       2  40대       E          1             1

   회원여부_이용가능_카드론  소지여부_신용  소지카드수_유효_신용  ...  할인금액_제휴연회비_B0M  청구금액_기본연회비_B0M  \
0              0        1            1  ...               0               0
1              1        1            1  ...               0               0
2              0        1            1  ...               0               0
3              0        1            2  ...               0               0
4              1        1            1  ...               0               0

   청구금액_제휴연회비_B0M  상품관련면제카드수_B0M  임직원면제카드수_B0M  우수회원면제카드수_B0M  기타면제카드수_B0M  \
0               0             0개            0개             0개           0개
1               0             0개            0개             0개           0개
2               0             0개            0개             0개           0개
3               0             0개            0개             0개           0개
4               0             0개            0개             0개           0개

   카드신청건수  Life_Stage  최종카드발급경과월
0       0     자녀성장(2)         22
1       0     자녀성장(1)         18
2       0       자녀출산기         20
3       1     자녀성장(2)         17
4       1     자녀성장(1)         15

[5 rows x 78 columns]

In [4]:
# 필요하면 하나로 합친 데이터 저장
merged_df.to_parquet('open/train/1.회원정보/2018_train_회원정보.parquet')
merged_df.to_csv('open/train/1.회원정보/2018_train_회원정보.csv')

In [5]:
df = pd.read_parquet ('open/train/1.회원정보/2018_train_회원정보.parquet')
df

,기준년월,ID,남녀구분코드,연령,Segment,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,...,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
0,201807,TRAIN_000000,2,40대,D,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(2),22
1,201807,TRAIN_000001,1,30대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),18
2,201807,TRAIN_000002,1,30대,C,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀출산기,20
3,201807,TRAIN_000003,2,40대,D,1,1,0,1,2,...,0,0,0,0개,0개,0개,0개,1,자녀성장(2),17
4,201807,TRAIN_000004,2,40대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,1,자녀성장(1),15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,2,70대이상,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,노년생활,39
2399996,201812,TRAIN_399996,2,50대,D,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(2),24
2399997,201812,TRAIN_399997,1,30대,C,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀출산기,18
2399998,201812,TRAIN_399998,1,40대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),27
2399999,201812,TRAIN_399999,2,40대,E,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),18